### PR TITLE
GitLab releases and `"branch": "release"` exceptions

### PR DESCRIPTION
**Pull request by wlandau**
* Automatically merge GitLab URLs with non-"upcoming" releases.
* Rename `build_universe()` to `write_universe_manifest()`. 
* `write_universe_manifest()` omits `"branch": "release"` from listings originating from a short list of prespecified GitHub/GitLab owners. The new `release_exceptions` can accept `"https://github.com/cran"`, for example.

### CODE REVIEW

**Comment by wlandau** [comment]
Notably, this PR fixes https://github.com/r-releases/help/issues/26 and https://github.com/r-releases/help/issues/31.

**Comment by wlandau** [comment]
@shikokuchuo, you will notice I called the GitHub API to check releases instead of the previous `ncurl()` approach. This is because the 302 redirect happens whether or not a release exists, so I don't think we were actually able to tell before.

**Comment by shikokuchuo** [comment]
Gitlab API you mean, not Github. I am aware of the redirect. It's also nothing to do with the client - same with curl or ncurl.

**Comment by wlandau** [comment]
Thanks!

**Comment by wlandau** [comment]
> Gitlab API you mean, not Github.

GitHub too, actually. 302 happens if there are tags but no releases:

```r
> nanonext::ncurl("https://github.com/apache/arrow/releases/latest")[["status"]] 
[1] 302
```

Same as repos with true releases:

```r
> nanonext::ncurl("https://github.com/ropensci/targets/releases/latest")[["status"]]
[1] 302
```

But 301 happens if there are neither tags nor releases:

```r
> nanonext::ncurl("https://github.com/wlandau/test-no-release/releases/latest")[["status"]]
[1] 301
```

**Pull request merged**
